version: '3.9'
services:
  backend:
    build: ./backend
    command: python -u app.py
    container_name: backend
    # restart: always
    ports: 
     - 5000:5000
    depends_on:
     - db

  db:
    image: mongo:6.0.1
    container_name: db
    hostname: db
    ports:
      - 27017:27017
    restart: 'always'
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
