version: '3.9'
services:
  db:
    image: mongo:6.0.1
    container_name: db
    hostname: db
    ports:
      - 27017:27017
    restart: 'always'

  backend:
    build: ./backend
    container_name: backend
    ports: 
     - 5000:5000
    depends_on:
     - db
    links:
     - db

  frontend:
    build: ./frontend/frontend
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    links:
      - backend