version: '3.9'
services:
  db:
    image: mongo:6.0.1
    platform: linux/x86_64 
    container_name: db
    ports:
      - 27017:27017
    restart: 'always'
    cap_add:
      - SYS_NICE # Deve omitir alertas menores