version: '3.9'
services:
  db:
    image: mongo:6.0.1
    container_name: db
    hostname: db
    ports:
      - 27017:27017
    restart: 'always'

  backend:
    build: ./backend
    container_name: backend
    # restart: always
    ports: 
     - 5000:5000
    depends_on:
     - db
    links:
     - db